apiVersion: v1
kind: Service
metadata:
  name: register-app-service
spec:
  type: NodePort
  selector:
    app: register-app
  ports:
    - name: http-app
      port: 5000
      targetPort: 5000
      nodePort: 30000
    - name: http-logger
      port: 5001
      targetPort: 5001
      nodePort: 30001
