apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
      - name: register-app
        image: register-app:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /app/db_data
          name: app-storage
      - name: logger
        image: register-app-logger:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        volumeMounts:
        - mountPath: /app/logs
          name: app-storage
      volumes:
      - name: app-storage
        emptyDir: {}
